name: Deploy Database

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-database:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install SQL Server Tools (sqlcmd)
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Run T-SQL script
        run: |
          # Connect using the secrets we configured
          sqlcmd -S ${{ secrets.SECRET_DB_HOST }} \
                 -U ${{ secrets.SECRET_DB_USER }} \
                 -P ${{ secrets.SECRET_DB_PASS }} \
                 -i init_database.sql