name: Deploy Database

on:
  workflow_dispatch:

jobs:
  deploy-development:
    uses: ./.github/workflows/deploy-sql-template.yml
    with:
      environment_name: development
      db_host: ${{ secrets.SECRET_DB_HOST }}
      db_user: ${{ secrets.SECRET_DB_USER }}
      db_pass: ${{ secrets.SECRET_DB_PASS }}
      sql_script: init_database.sql

  deploy-production:
    needs: deploy-development
    uses: ./.github/workflows/deploy-sql-template.yml
    with:
      environment_name: production
      db_host: "0.tcp.in.ngrok.io,15874"
      db_user: ${{ secrets.SECRET_DB_USER_PROD }}
      db_pass: ${{ secrets.SECRET_DB_PASS_PROD }}
      sql_script: init_database.sql
