name: Deploy Database

on:
  workflow_dispatch:

jobs:
  deploy-development:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Deploy to Development
        uses: ./.github/workflows/deploy_db_reusable.yml
        with:
          db-host: ${{ secrets.SECRET_DB_HOST }}
          db-user: ${{ secrets.SECRET_DB_USER }}
          db-pass: ${{ secrets.SECRET_DB_PASS }}
          environment-name: "development"
          sql-script: "init_database.sql"

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-development
    environment: production
    steps:
      - name: Deploy to Production
        uses: ./.github/workflows/deploy_db_reusable.yml
        with:
          db-host: "0.tcp.in.ngrok.io,10901"
          db-user: ${{ secrets.SECRET_DB_USER_PROD }}
          db-pass: ${{ secrets.SECRET_DB_PASS_PROD }}
          environment-name: "production"
          sql-script: "init_database.sql"
