name: Deploy SQL Template

on:
  workflow_call:
    inputs:
      environment_name:
        required: true
        type: string
      db_host:
        required: true
        type: string
      db_user:
        required: true
        type: string
      db_pass:
        required: true
        type: string
      sql_script:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment_name }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      
      - name: Run T-SQL script
        run: |
          export PATH="$PATH:/opt/mssql-tools18/bin"
          
          # Trim whitespace from credentials
          DB_USER=$(echo "${{ inputs.db_user }}" | tr -d '\n' | xargs)
          DB_PASS=$(echo "${{ inputs.db_pass }}" | tr -d '\n' | xargs)
          
          sqlcmd -S "${{ inputs.db_host }}" \
                 -U "$DB_USER" \
                 -P "$DB_PASS" \
                 -i "${{ inputs.sql_script }}" \
                 -N -C
