name: Deploy Database

on:
  workflow_dispatch:

jobs:
  deploy-development:
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: "development"
    secrets:
      db_host: ${{ secrets.SECRET_DB_HOST }}
      db_user: ${{ secrets.SECRET_DB_USER }}
      db_pass: ${{ secrets.SECRET_DB_PASS }}

  deploy-production:
    needs: deploy-development
    uses: ./.github/workflows/deploy_template.yml
    with:
      environment: "production"
    secrets:
      db_host: "0.tcp.in.ngrok.io,10901"
      db_user: ${{ secrets.SECRET_DB_USER_PROD }}
      db_pass: ${{ secrets.SECRET_DB_PASS_PROD }}
