name: Deploy Database

on:
  workflow_dispatch:

jobs:
  deploy-development:
    uses: ./.github/workflows/deploy-sql-template.yml
    with:
      environment_name: development
      sql_script: init_database.sql
    secrets:
      SECRET_DB_HOST: ${{ secrets.SECRET_DB_HOST }}
      SECRET_DB_USER: ${{ secrets.SECRET_DB_USER }}
      SECRET_DB_PASS: ${{ secrets.SECRET_DB_PASS }}

  deploy-production:
    needs: deploy-development
    uses: ./.github/workflows/deploy-sql-template.yml
    with:
      environment_name: production
      sql_script: init_database.sql
    secrets:
      SECRET_DB_USER_PROD: ${{ secrets.SECRET_DB_USER_PROD }}
      SECRET_DB_PASS_PROD: ${{ secrets.SECRET_DB_PASS_PROD }}
