name: Deploy Database

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-development:
    runs-on: ubuntu-latest
    environment: development  # Define the development environment
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install SQL Server Tools (sqlcmd)
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg2 apt-transport-https
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /usr/share/keyrings/microsoft-prod.gpg > /dev/null
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-prod.gpg] https://packages.microsoft.com/ubuntu/24.04/prod noble main" | sudo tee /etc/apt/sources.list.d/mssql-tools.list
          sudo apt-get update
          sudo apt-get install -y mssql-tools18 unixodbc-dev

      - name: Run T-SQL script for Development
        run: |
          export PATH="$PATH:/opt/mssql-tools18/bin"
          sqlcmd -S ${{ secrets.DEV_DB_HOST }} \
                 -U ${{ secrets.DEV_DB_USER }} \
                 -P ${{ secrets.DEV_DB_PASS }} \
                 -i init_database.sql \
                 -N -C

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-development  # Wait for the development job to complete
    environment: production    # Define the production environment with approval
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install SQL Server Tools (sqlcmd)
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg2 apt-transport-https
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /usr/share/keyrings/microsoft-prod.gpg > /dev/null
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-prod.gpg] https://packages.microsoft.com/ubuntu/24.04/prod noble main" | sudo tee /etc/apt/sources.list.d/mssql-tools.list
          sudo apt-get update
          sudo apt-get install -y mssql-tools18 unixodbc-dev

      - name: Run T-SQL script for Production
        run: |
          export PATH="$PATH:/opt/mssql-tools18/bin"
          sqlcmd -S ${{ secrets.PROD_DB_HOST }} \
                 -U ${{ secrets.PROD_DB_USER }} \
                 -P ${{ secrets.PROD_DB_PASS }} \
                 -i init_database.sql \
                 -N -C
