name: Database Deployment Pipeline

on: [workflow_dispatch]

jobs:
  dev-deployment:
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: dev
    secrets:
      SQL_SERVER: ${{ secrets.DB_SQL_SERVER }}
      SQL_USER: ${{ secrets.DB_SQL_USER }}
      SQL_PASSWORD: ${{ secrets.DB_SQL_PASSWORD }}

  prod-deployment:
    needs: dev-deployment
    if: success()
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: production
    secrets:
      SQL_SERVER: ${{ secrets.PROD_SQL_SERVER }}
      SQL_USER: ${{ secrets.PROD_SQL_USER }}
      SQL_PASSWORD: ${{ secrets.PROD_SQL_PASSWORD }}
